# Generated by Django 5.0.6 on 2024-12-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape_design_app', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
