# Generated by Django 5.1.6 on 2025-03-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landscape_design_app', '0004_service'),
    ]

    operations = [
    ]
