# Generated by Django 5.1.6 on 2025-03-30 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape_design_app', '0007_blogcategory_blogtag_contact_portfoliocategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(help_text='Уникальная строка для URL (генерируется автоматически, если пусто)', unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(help_text='Уникальная строка для URL (генерируется автоматически, если пусто)', unique=True, verbose_name='URL slug'),
        ),
    ]
